name: CI Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        sudo apt-get install -y chromium-chromedriver
        export CHROME_BIN=$(which google-chrome)
        export CHROME_DRIVER=$(which chromedriver)

    - name: Verify Chrome installation
      run: |
        echo "Google Chrome binary location: $CHROME_BIN"
        echo "Google Chrome version: $($CHROME_BIN --version)"
        echo "ChromeDriver binary location: $CHROME_DRIVER"
        echo "ChromeDriver version: $($CHROME_DRIVER --version)"

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Generate Allure report
      run: mvn allure:report

    - name: Publish Allure report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: target/site/allure-maven/index.html
