name: CI Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip curl ca-certificates

    - name: Install Google Chrome (specific version)
      run: |
        wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_115.0.5790.102-1_amd64.deb -O google-chrome.deb
        sudo apt install -y ./google-chrome.deb
        google-chrome --version

    - name: Install ChromeDriver (matching version)
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
        echo "Using Chrome version: $CHROME_VERSION"
        CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        echo "Detected ChromeDriver version: $CHROMEDRIVER_VERSION"
        wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version

    - name: Verify installation
      run: |
        google-chrome --version
        chromedriver --version

    - name: Set environment variables
      run: |
        echo "CHROME_BIN=/usr/bin/google-chrome" >> $GITHUB_ENV
        echo "CHROME_DRIVER=/usr/local/bin/chromedriver" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Generate Allure report
      run: mvn allure:report

    - name: Publish Allure report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: target/site/allure-maven/index.html
