name: CI Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: 'QA'
        type: choice
        options:
          - QA
          - DEV
          - SANDBOX
          - STAGING
          - UAT
          - PROD
      test_suite:
        description: "Select the test suite to run"
        required: true
        type: choice
        options:
          - 'StepDefinitionsTest'
          - 'allTests'
          - 'regressionTests'
          - 'smokeTests'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl ca-certificates

      - name: Install Google Chrome
        run: |
          curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o google-chrome.deb
          sudo apt install -y ./google-chrome.deb
          google-chrome --version

      - name: Install ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          echo "Forcing ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Verify installation
        run: |
          google-chrome --version
          chromedriver --version

      - name: Set environment variables
        run: |
          echo "CHROME_BIN=/usr/bin/google-chrome" >> $GITHUB_ENV
          echo "CHROME_DRIVER=/usr/local/bin/chromedriver" >> $GITHUB_ENV
          echo "BASE_URL=https://www.google.com" >> $GITHUB_ENV  # Establecer URL base válida
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "TEST_SUITE=${{ github.event.inputs.test_suite }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test -Dtest=${{ github.event.inputs.test_suite }} -Denv=${{ github.event.inputs.environment }} -DbaseUrl=${{ secrets.BASE_URL }} -DapiKey=${{ secrets.API_KEY }}

      - name: Generate Allure report
        run: mvn allure:report

      - name: Publish Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report
